language: node_js

script:
  - "npm run ci"

before_script:
  - 'if [ "$REACT_VERSION" ]; then npm i react@$REACT_VERSION react-dom@$REACT_VERSION ; fi'

node_js:
  - "13"
  - "12"
  - "10"

branches:
  except:
    - /^v\d+\./

matrix:
  fast_finish: true
  include:
    - node_js: "12"
      env: COVERAGE=true
    - node_js: "12"
      env: REACT_VERSION=16.12.0
    - node_js: "12"
      env: REACT_VERSION=16.11.0
    - node_js: "12"
      env: REACT_VERSION=16.10.2
    - node_js: "12"
      env: REACT_VERSION=16.10.1
    - node_js: "12"
      env: REACT_VERSION=16.10.0
    - node_js: "12"
      env: REACT_VERSION=16.9.0
    - node_js: "12"
      env: REACT_VERSION=16.8.6
    - node_js: "12"
      env: REACT_VERSION=16.8.5
    - node_js: "12"
      env: REACT_VERSION=16.8.4
    - node_js: "12"
      env: REACT_VERSION=16.8.3
    - node_js: "12"
      env: REACT_VERSION=16.8.2
    - node_js: "12"
      env: REACT_VERSION=16.8.1
    - node_js: "12"
      env: REACT_VERSION=16.8.0
  allow_failures:
    - env: COVERAGE=true

cache: npm
